const START_TIME = 75;
const THRESHHOLD = {
  ONE_STAR: 40,
  TWO_STAR: 70,
  THREE_STAR: 90,
}
const LEVELS_TO_ADVANCE = {
  ONE_STAR: 1,
  TWO_STAR: 2,
  THREE_STAR: 3,
}
const COUNTDOWN = 3;
const RUNNING_OUT_OF_TIME = 10;

export {
  START_TIME,
  THRESHHOLD,
  COUNTDOWN,
  LEVELS_TO_ADVANCE,
  RUNNING_OUT_OF_TIME
};
